# Generated by Django 5.1 on 2025-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='specialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(default='', max_length=50)),
                ('offer_description', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(help_text='This will be your main image.', upload_to='special-offer-images')),
            ],
        ),
        migrations.CreateModel(
            name='TopBannerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default='', max_length=50)),
                ('banner_description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
