# Generated by Django 5.1 on 2025-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBannerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default='', max_length=50)),
                ('banner_description', models.TextField(max_length=500)),
            ],
        ),
    ]
