# Generated by Django 5.1 on 2025-01-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ingredients',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
                ('category_url', models.SlugField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='', max_length=20)),
                ('added_percentage', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_must_try', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', help_text='Tell your customers what makes this product awesome! Share its benefits, key ingredients, and how to use it. Keep it simple and clear so they know why they’ll love it.')),
                ('size', models.CharField(blank=True, default='', help_text="IGNORE THIS MY DEAR! It'll prepopulate itself.", max_length=20, null=True)),
                ('image_1', models.ImageField(help_text='This will be your main image.', upload_to='product-images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for the SMALLEST size', max_digits=10)),
                ('stock', models.IntegerField()),
                ('product_details', models.TextField(blank=True, default='', null=True)),
                ('how_to_use', models.TextField(blank=True, default='', null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='KaSheaCosmetics_products.ingredients')),
                ('category', models.ForeignKey(default='', help_text='Pick a category from the dropdown, or, add one using the + button.', on_delete=django.db.models.deletion.CASCADE, to='KaSheaCosmetics_products.productcategory')),
                ('product_sizes', models.ManyToManyField(to='KaSheaCosmetics_products.productsize')),
                ('shipping_option', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KaSheaCosmetics_products.shippingoption')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('product_rating', models.PositiveIntegerField()),
                ('review_title', models.CharField(default='', max_length=100)),
                ('review_content', models.TextField(default='', max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review-images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='KaSheaCosmetics_products.product')),
            ],
        ),
    ]
