# Generated by Django 5.1 on 2024-08-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KaSheaCosmetics_products.shippingoption'),
        ),
    ]
