# Generated by Django 5.1 on 2024-11-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', help_text='Pick a category from the dropdown, or, add one using the + button.', on_delete=django.db.models.deletion.CASCADE, to='KaSheaCosmetics_products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='Tell your customers what makes this product awesome! Share its benefits, key ingredients, and how to use it. Keep it simple and clear so they know why they’ll love it.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(help_text='This will be your main image.', upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price for the SMALLEST size', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', help_text="IGNORE THIS MY DEAR! It'll prepopulate itself.", max_length=20, null=True),
        ),
    ]
