# Generated by Django 5.1 on 2025-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_products', '0003_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ingredients', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='product',
            name='you_must_try',
            field=models.BooleanField(default=False),
        ),
    ]
