# Generated by Django 5.1 on 2024-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_products', '0004_productcategory_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_url',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
    ]
