# Generated by Django 5.1 on 2024-09-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
