# Generated by Django 5.1 on 2024-10-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_orders', '0002_rename_create_at_order_created_at'),
        ('KaSheaCosmetics_products', '0006_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KaSheaCosmetics_products.productsize'),
        ),
    ]
