# Generated by Django 5.1 on 2024-08-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KaSheaCosmetics_products', '0003_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_emails', to='KaSheaCosmetics_products.product')),
            ],
        ),
    ]
