# Generated by Django 5.1 on 2025-01-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaSheaCosmetics_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeremails',
            options={'verbose_name': 'Customer Email', 'verbose_name_plural': 'Customer Emails'},
        ),
    ]
